apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}-test
  namespace: {{ .Values.namesp }}
  labels:
    app: {{ .Values.name }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
       app: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.nginx.image }}
        name: nginx-{{ .Values.name }}
